#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.9.1 */
/* https://trip5.github.io/ehRadio_myoptions/generator.html?b=ESP32-S3_Module&r=72,1,2,4,9,73,42,43,54,55&i=1,2,3,4,15,16,17,28,29,30,31,32,33&v=10,11,-1,9,48,47,21,5,6,7,16,17,18 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */

/* !!! Attention !!! */
/* This configuration depends on some additional libraries. Please install them using the library manager: */
/* Adafruit GFX Library, OneButton */

/* !!! Do not be alarmed by some #defines missing. Default values are not included in this file. !!! */
/* !!! Values of 255 must be edited before using (except I2S_DOUT 255 which is used to disable I2S Sound). !!! */

#define ARDUINO_ESP32S3_DEV

#define BITRATE_FULL true
#define SSD1322_GRAYSCALE         true
#define L10N_LANGUAGE			RU
#define DSP_MODEL			DSP_SSD1322
#define TFT_DC			10
#define TFT_CS			9
#define TFT_RST			-1
#define BRIGHTNESS_PIN			255
#define I2S_DOUT			48
#define I2S_BCLK			47
#define I2S_LRC			21
#define VS1053_CS     255
#define ENC_BTNR			5
#define ENC_BTNL			6
#define ENC_BTNB			7
#define ENC_INTERNALPULLUP			false
#define ENC2_BTNR			16
#define ENC2_BTNL			17
#define ENC2_BTNB			18
#define ENC2_INTERNALPULLUP			false

// #define IR_PIN 15
// #define WEATHER true
// #define IR_TIMEOUT 20
#endif